# Generated by Django 2.1.3 on 2018-11-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('revision', models.CharField(max_length=10)),
                ('bjcp_class', models.CharField(choices=[('beer', 'Beer'), ('cider', 'Cider'), ('mead', 'Mead')], max_length=10)),
                ('category', models.CharField(max_length=2)),
                ('subcategory', models.CharField(max_length=2)),
                ('category_name', models.CharField(max_length=255)),
                ('category_notes', models.CharField(max_length=255)),
                ('ibu_low', models.FloatField(null=True)),
                ('ibu_high', models.FloatField(null=True)),
                ('og_low', models.FloatField(null=True)),
                ('og_high', models.FloatField(null=True)),
                ('fg_low', models.FloatField(null=True)),
                ('fg_high', models.FloatField(null=True)),
                ('srm_low', models.FloatField(null=True)),
                ('srm_high', models.FloatField(null=True)),
                ('abv_low', models.FloatField(null=True)),
                ('abv_high', models.FloatField(null=True)),
                ('aroma', models.CharField(blank=True, max_length=255, null=True)),
                ('appearance', models.CharField(blank=True, max_length=255, null=True)),
                ('flavor', models.CharField(blank=True, max_length=255, null=True)),
                ('mouthfeel', models.CharField(blank=True, max_length=255, null=True)),
                ('impression', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('history', models.CharField(blank=True, max_length=255, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=255, null=True)),
                ('comparison', models.CharField(blank=True, max_length=255, null=True)),
                ('examples', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
