# Generated by Django 2.1.3 on 2018-11-04 17:30

from django.db import migrations, models
import django_countries.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('time_zone', timezone_field.fields.TimeZoneField(default='America/Chicago')),
                ('website', models.URLField(blank=True)),
                ('facebook_page', models.URLField(blank=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=25)),
                ('instagram_handle', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
