# Generated by Django 2.1.3 on 2018-11-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='tap_list_provider',
            field=models.CharField(blank=True, choices=[('untappd', 'Untappd'), ('digitalpour', 'DigitalPour'), ('taphunter', 'TapHunter'), ('nook_html', "The Nook's static HTML"), ('manual', 'Chalkboard/Whiteboard'), ('', 'Unknown')], max_length=30, verbose_name='What service the venue uses for digital tap lists'),
        ),
    ]
