# Generated by Django 2.1.3 on 2018-11-06 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venueapiconfiguration_squashed_0004_auto_20181105_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='venues.Venue')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('venue', 'name')},
        ),
    ]
