# Generated by Django 2.1.7 on 2019-02-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taps', '0006_auto_20190217_2129'),
        ('venues', '0009_venue_untappd_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='room',
            name='venue',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
