# Generated by Django 2.2 on 2019-04-17 02:13

from django.db import migrations


def drop_madison_taproom(apps, schema_editor):
    venue = apps.get_model('venues.Venue')
    beer_price = apps.get_model('beers.BeerPrice')
    beer_price.objects.filter(venue__id=2).delete()
    venue.objects.filter(id=2).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0012_auto_20190328_1915'),
    ]

    operations = [
        migrations.RunPython(drop_madison_taproom, migrations.RunPython.noop),
    ]
