# Generated by Django 2.2 on 2019-04-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0013_drop_madison_taproom'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
