# Generated by Django 2.2.1 on 2019-05-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0018_auto_20190503_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='on_downtown_craft_beer_trail',
            field=models.NullBooleanField(default=False),
        ),
    ]
