# Generated by Django 2.2.1 on 2019-05-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0020_populate_on_craft_beer_trail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='on_downtown_craft_beer_trail',
            field=models.BooleanField(default=False),
        ),
    ]
