# Generated by Django 2.2.3 on 2019-07-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0022_venueapiconfiguration_taphunter_excluded_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='tap_list_provider',
            field=models.CharField(blank=True, choices=[('untappd', 'Untappd'), ('digitalpour', 'DigitalPour'), ('taphunter', 'TapHunter'), ('manual', 'Chalkboard/Whiteboard'), ('', 'Unknown'), ('test', 'TEST LOCAL PROVIDER'), ('stemandstein', "The Stem & Stein's HTML"), ('taplist.io', 'taplist.io')], max_length=30, verbose_name='What service the venue uses for digital tap lists'),
        ),
    ]
