# Generated by Django 3.0.1 on 2020-01-12 23:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0025_venue_twitter_short_location_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueapiconfiguration',
            name='beermenus_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='venueapiconfiguration',
            name='beermenus_slug',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='venue',
            name='tap_list_provider',
            field=models.CharField(blank=True, choices=[('untappd', 'Untappd'), ('digitalpour', 'DigitalPour'), ('taphunter', 'TapHunter'), ('manual', 'Chalkboard/Whiteboard'), ('', 'Unknown'), ('test', 'TEST LOCAL PROVIDER'), ('stemandstein', "The Stem & Stein's HTML"), ('taplist.io', 'taplist.io'), ('beermenus', 'BeerMenus')], max_length=30, verbose_name='What service the venue uses for digital tap lists'),
        ),
    ]
