# Generated by Django 3.1.2 on 2020-11-15 14:59

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0028_auto_20201014_1424"),
    ]

    operations = [
        migrations.AddField(
            model_name="venueapiconfiguration",
            name="arryved_location_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="venueapiconfiguration",
            name="arryved_manufacturer_name",
            field=django.contrib.postgres.fields.citext.CITextField(blank=True),
        ),
        migrations.AddField(
            model_name="venueapiconfiguration",
            name="arryved_menu_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="venue",
            name="tap_list_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("untappd", "Untappd"),
                    ("digitalpour", "DigitalPour"),
                    ("taphunter", "TapHunter"),
                    ("manual", "Chalkboard/Whiteboard"),
                    ("", "Unknown"),
                    ("test", "TEST LOCAL PROVIDER"),
                    ("stemandstein", "The Stem & Stein's HTML"),
                    ("taplist.io", "taplist.io"),
                    ("beermenus", "BeerMenus"),
                    ("arryved_embedded_menu", "Arryved Embedded Menu"),
                ],
                max_length=30,
                verbose_name="What service the venue uses for digital tap lists",
            ),
        ),
    ]
