# Generated by Django 3.1.2 on 2020-10-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0028_create_venue_manager_model"),
        ("venues", "0028_auto_20201014_1424"),
    ]

    operations = []
