# Generated by Django 3.1.2 on 2020-11-17 01:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0029_auto_20201115_1459"),
    ]

    operations = [
        migrations.AddField(
            model_name="venueapiconfiguration",
            name="arryved_serving_sizes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
