# Generated by Django 3.1.2 on 2020-11-18 16:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0029_auto_20201115_1459_squashed_0031_auto_20201117_0143"),
    ]

    operations = [
        migrations.AddField(
            model_name="venueapiconfiguration",
            name="arryved_pos_menu_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                help_text="Individual menus to process from the Arryved POS",
                null=True,
                size=None,
            ),
        ),
    ]
