# Generated by Django 3.1.2 on 2020-11-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0030_venueapiconfiguration_arryved_pos_menu_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="tap_list_provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("untappd", "Untappd"),
                    ("digitalpour", "DigitalPour"),
                    ("taphunter", "TapHunter"),
                    ("manual", "Chalkboard/Whiteboard"),
                    ("", "Unknown"),
                    ("test", "TEST LOCAL PROVIDER"),
                    ("stemandstein", "The Stem & Stein's HTML"),
                    ("taplist.io", "taplist.io"),
                    ("beermenus", "BeerMenus"),
                    ("arryved_embedded_menu", "Arryved Embedded Menu"),
                    ("arryved_pos_menu", "Arryved Point of Sale Menu"),
                ],
                max_length=30,
                verbose_name="What service the venue uses for digital tap lists",
            ),
        ),
    ]
