# Generated by Django 3.1.3 on 2020-11-24 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0031_auto_20201119_2230"),
        ("venues", "0028_create_venue_manager_model"),
    ]

    operations = []
