# Generated by Django 4.2.1 on 2023-05-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0032_merge_20201124_1755"),
        ("beers", "0040_create_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venueapiconfiguration",
            name="arryved_manufacturer_name",
            field=models.TextField(blank=True, db_collation="case_insensitive"),
        ),
    ]
