# Generated by Django 2.1.3 on 2018-11-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
