# Generated by Django 2.1.3 on 2018-11-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('revision', models.CharField(max_length=10)),
                ('bjcp_class', models.CharField(choices=[('beer', 'Beer'), ('cider', 'Cider'), ('mead', 'Mead')], max_length=10)),
                ('category', models.CharField(max_length=2)),
                ('subcategory', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=1)),
                ('category_name', models.CharField(max_length=255)),
                ('category_notes', models.CharField(max_length=255)),
                ('ibu_low', models.PositiveSmallIntegerField(default=0)),
                ('ibu_high', models.PositiveSmallIntegerField(default=0)),
                ('srm_low', models.PositiveSmallIntegerField(default=0)),
                ('srm_high', models.PositiveSmallIntegerField(default=0)),
                ('og_low', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('og_high', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('fg_low', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('fg_high', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('abv_low', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('abv_high', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('aroma', models.CharField(blank=True, default='', max_length=255)),
                ('appearance', models.CharField(blank=True, default='', max_length=255)),
                ('flavor', models.CharField(blank=True, default='', max_length=255)),
                ('mouthfeel', models.CharField(blank=True, default='', max_length=255)),
                ('impression', models.CharField(blank=True, default='', max_length=255)),
                ('comments', models.CharField(blank=True, default='', max_length=255)),
                ('history', models.CharField(blank=True, default='', max_length=255)),
                ('ingredients', models.CharField(blank=True, default='', max_length=255)),
                ('comparison', models.CharField(blank=True, default='', max_length=255)),
                ('examples', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
