# Generated by Django 2.1.3 on 2018-11-17 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerstyletag',
            name='tag',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='beerstyle',
            unique_together={('category', 'subcategory')},
        ),
        migrations.AlterUniqueTogether(
            name='beerstylecategory',
            unique_together={('category_id', 'revision', 'bjcp_class')},
        ),
    ]
