# Generated by Django 2.1.3 on 2018-12-03 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('in_production', models.BooleanField(default=True)),
                ('abv', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Alcohol content (% by volume)')),
                ('ibu', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bitterness (International Bitterness Units)')),
                ('color_srm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Color (Standard Reference Method)')),
                ('untappd_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Untappd ID (if known)')),
                ('beer_advocate_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='BeerAdvocate ID (if known)')),
                ('rate_beer_url', models.URLField(blank=True, null=True, unique=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beers', to='beers.Manufacturer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='beer',
            unique_together={('name', 'manufacturer')},
        ),
    ]
