# Generated by Django 2.1.3 on 2018-12-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_beer_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerstyle',
            name='abv_high',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Minimum alcohol content (% by volume)'),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='abv_low',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Maximum alcohol content (% by volume)'),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='fg_high',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Maximum final specific gravity'),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='fg_low',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Minimum final specific gravity'),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='ibu_high',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Maximum bitterness (International Bitterness Units)'),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='ibu_low',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Minimum bitterness (International Bitterness Units)'),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='og_high',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Maximum original specific gravity'),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='og_low',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='Minimum original specific gravity'),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='srm_high',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Maximum color (Standard Reference Method)'),
        ),
        migrations.AlterField(
            model_name='beerstyle',
            name='srm_low',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Minimum color (Standard Reference Method)'),
        ),
    ]
