# Generated by Django 2.1.3 on 2018-12-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_auto_20181204_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
