# Generated by Django 2.1.5 on 2019-02-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0008_auto_20190202_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
