# Generated by Django 2.1.7 on 2019-02-17 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0011_auto_20190215_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='beer_advocate_id',
        ),
        migrations.AddField(
            model_name='beer',
            name='beer_advocate_url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='BeerAdvocate URL (if known)'),
        ),
        migrations.AddField(
            model_name='beer',
            name='manufacturer_url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
