# Generated by Django 2.1.7 on 2019-03-28 20:28

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0018_prepare_for_case_insensitive_beers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='name',
            field=django.contrib.postgres.fields.citext.CITextField(),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=django.contrib.postgres.fields.citext.CITextField(unique=True),
        ),
    ]
