# Generated by Django 2.2 on 2019-04-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0024_populate_styles'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='beerstylecategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='beer',
            name='style',
        ),
        migrations.DeleteModel(
            name='BeerStyle',
        ),
        migrations.DeleteModel(
            name='BeerStyleCategory',
        ),
        migrations.DeleteModel(
            name='BeerStyleTag',
        ),
    ]
