# Generated by Django 2.2 on 2019-05-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0025_auto_20190409_0145_squashed_0026_auto_20190409_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='taplist_io_pk',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='taplist_io_pk',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
