# Generated by Django 2.2 on 2019-04-09 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0025_auto_20190409_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='new_style',
            new_name='style',
        ),
    ]
