# Generated by Django 2.2.1 on 2019-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0027_add_alt_innerspace_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='default_color',
            field=models.CharField(blank=True, max_length=9, verbose_name='HTML color (in hex) to use if the beer has no known color'),
        ),
    ]
