# Generated by Django 2.2 on 2019-05-14 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0027_add_alt_innerspace_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='time_first_seen',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='time_first_seen',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
