# Generated by Django 2.2.1 on 2019-05-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0028_auto_20190514_1914'),
        ('beers', '0028_style_default_color'),
    ]

    operations = [
    ]
