# Generated by Django 2.2.4 on 2019-08-22 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0030_auto_20190807_2142'),
        ('beers', '0030_userfavoritebeer'),
    ]

    operations = [
    ]
