# Generated by Django 2.2.7 on 2019-11-15 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0030_userfavoritebeer"),
        ("beers", "0031_beer_tweeted_about"),
    ]

    operations = []
