# Generated by Django 3.0.2 on 2020-01-24 20:44

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0032_auto_20200112_2339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beer",
            name="beer_advocate_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="BeerAdvocate URL (if known)"
            ),
        ),
        migrations.AlterField(
            model_name="beer",
            name="beermenus_slug",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="beer",
            name="manufacturer_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beer",
            name="rate_beer_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beer",
            name="stem_and_stein_pk",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beer",
            name="taphunter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beer",
            name="taplist_io_pk",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="beer",
            name="tweeted_about",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="beer",
            name="untappd_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="beermenus_slug",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=django.contrib.postgres.fields.citext.CITextField(),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="taphunter_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="taplist_io_pk",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="untappd_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stylealternatename",
            name="name",
            field=django.contrib.postgres.fields.citext.CITextField(),
        ),
        migrations.AlterUniqueTogether(
            name="beer",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="beerprice",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="beer",
            index=models.Index(
                fields=["tweeted_about"], name="beers_beer_tweeted_5dc5f1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("abv__gte", 0), ("abv__lte", 100)),
                    ("abv__isnull", True),
                    _connector="OR",
                ),
                name="abv_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("ibu__lte", 1000), ("ibu__isnull", True), _connector="OR"
                ),
                name="ibu_not_unreal",
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.UniqueConstraint(
                fields=("beermenus_slug",), name="unique_beermenus_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.UniqueConstraint(
                fields=("taplist_io_pk",), name="unique_taplist_io_pk"
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.UniqueConstraint(
                fields=("stem_and_stein_pk",), name="unique_stem_and_stein_pk"
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.UniqueConstraint(
                fields=("taphunter_url",), name="unique_taphunter_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.UniqueConstraint(
                fields=("manufacturer_url",), name="unique_manufacturer_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.UniqueConstraint(
                fields=("rate_beer_url",), name="unique_rate_beer_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.UniqueConstraint(
                fields=("untappd_url",), name="unique_untappd_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.UniqueConstraint(
                fields=("beer_advocate_url",), name="unique_beer_advocate_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="beer",
            constraint=models.UniqueConstraint(
                fields=("name", "manufacturer"), name="unique_beer_per_manufacturer"
            ),
        ),
        migrations.AddConstraint(
            model_name="beerprice",
            constraint=models.UniqueConstraint(
                fields=("beer", "venue", "serving_size"), name="beer_venue_servingsize"
            ),
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_mfg_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.UniqueConstraint(
                fields=("taplist_io_pk",), name="unique_mfg_taplist_io_pk"
            ),
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.UniqueConstraint(
                fields=("taphunter_url",), name="unique_mfg_taphunter_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.UniqueConstraint(
                fields=("untappd_url",), name="unique_mfg_untappd_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="manufacturer",
            constraint=models.UniqueConstraint(
                fields=("beermenus_slug",), name="unique_mfg_beermenus_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="stylealternatename",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_alt_name_name"
            ),
        ),
    ]
