# Generated by Django 3.0.7 on 2020-06-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0034_auto_20200602_2202"),
        ("beers", "0032_merge_20191115_0316"),
    ]

    operations = []
