# Generated by Django 3.1.2 on 2020-11-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0034_auto_20200602_2202"),
    ]

    operations = [
        migrations.AlterField(
            model_name="untappdmetadata",
            name="json_data",
            field=models.JSONField(),
        ),
    ]
