# Generated by Django 3.1.2 on 2020-11-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0035_auto_20201112_1657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beer",
            name="automatic_updates_blocked",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="automatic_updates_blocked",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
