# Generated by Django 3.1.2 on 2020-11-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0035_auto_20201015_2057"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beer",
            name="taphunter_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="TapHunter URL (if known)"
            ),
        ),
    ]
