# Generated by Django 3.1.2 on 2020-11-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0035_merge_20200623_1127"),
        ("beers", "0036_auto_20201112_1705"),
    ]

    operations = []
