# Generated by Django 3.1.2 on 2020-11-14 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0036_auto_20201112_1705"),
        ("beers", "0036_auto_20201101_1209"),
    ]

    operations = []
