# Generated by Django 3.1.7 on 2021-02-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0037_merge_20201114_1252"),
        ("beers", "0037_merge_20201120_1718"),
    ]

    operations = []
