# Generated by Django 3.2.4 on 2022-09-13 17:58

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.apps.registry import Apps
from django.db import migrations, models
import django.db.models.deletion


def populate_alternate_names_array(apps: Apps, schema_editor):
    beer_model = apps.get_model("beers.beer")
    for beer in beer_model.objects.prefetch_related("alternate_names_old"):
        beer.alternate_names = [
            old_name.name for old_name in beer.alternate_names_old.all()
        ]
        beer.save()
    manufacturer_model = apps.get_model("beers.manufacturer")
    for mfg in manufacturer_model.objects.prefetch_related("alternate_names_old"):
        mfg.alternate_names = [
            old_name.name for old_name in mfg.alternate_names_old.all()
        ]
        mfg.save()
    style_model = apps.get_model("beers.style")
    for style in style_model.objects.prefetch_related("alternate_names_old"):
        style.alternate_names = [
            old_name.name for old_name in style.alternate_names_old.all()
        ]
        style.save()


def populate_alternate_names_fk(apps: Apps, schema_editor):
    beer_model = apps.get_model("beers.beer")
    manufacturer_model = apps.get_model("beers.manufacturer")
    style_model = apps.get_model("beers.style")
    beer_alt_name_model = apps.get_model("beers.beeralternatename")
    style_alt_name_model = apps.get_model("beers.stylealternatename")
    manufacturer_alt_name_model = apps.get_model("beers.manufactureralternatename")
    beer_alt_names = []
    mfg_alt_names = []
    style_alt_names = []
    for beer in beer_model.objects.all():
        beer_alt_names.extend(
            beer_alt_name_model(beer=beer, name=name) for name in beer.alternate_names
        )
    for style in style_model.objects.all():
        style_alt_names.extend(
            style_alt_name_model(style=style, name=name)
            for name in style.alternate_names
        )
    for mfg in manufacturer_model.objects.all():
        mfg_alt_names.extend(
            manufacturer_alt_name_model(manufacturer=mfg, name=name)
            for name in mfg.alternate_names
        )
    beer_alt_name_model.objects.bulk_create(beer_alt_names, batch_size=500)
    manufacturer_alt_name_model.objects.bulk_create(mfg_alt_names, batch_size=500)
    style_alt_name_model.objects.bulk_create(style_alt_names, batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0037_merge_20201114_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="beer",
            name="alternate_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.citext.CITextField(),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="alternate_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.citext.CITextField(),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="style",
            name="alternate_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.citext.CITextField(),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="beeralternatename",
            name="beer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternate_names_old",
                to="beers.beer",
            ),
        ),
        migrations.AlterField(
            model_name="manufactureralternatename",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternate_names_old",
                to="beers.manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="stylealternatename",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternate_names_old",
                to="beers.style",
            ),
        ),
        migrations.RunPython(
            populate_alternate_names_array, populate_alternate_names_fk
        ),
        migrations.RemoveField(
            model_name="manufactureralternatename",
            name="manufacturer",
        ),
        migrations.RemoveField(
            model_name="stylealternatename",
            name="style",
        ),
        migrations.DeleteModel(
            name="BeerAlternateName",
        ),
        migrations.DeleteModel(
            name="ManufacturerAlternateName",
        ),
        migrations.DeleteModel(
            name="StyleAlternateName",
        ),
    ]
