# Generated by Django 3.2.15 on 2022-09-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0038_auto_20220913_1758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="location",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
