"""Create a case-insensitive collation for replacing the CITextField"""

# Generated by Django 4.2.1 on 2023-05-22 19:29

from django.db import migrations
from django.contrib.postgres.operations import CreateCollation


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0039_alter_manufacturer_location"),
    ]

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="und-u-ks-level2",
            deterministic=False,
        )
    ]
