# Generated by Django 4.2.1 on 2023-05-22 19:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0040_create_collation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beer",
            name="alternate_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(db_collation="case_insensitive"),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="beer",
            name="name",
            field=models.TextField(db_collation="case_insensitive"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="alternate_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(db_collation="case_insensitive"),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.TextField(db_collation="case_insensitive"),
        ),
        migrations.AlterField(
            model_name="style",
            name="alternate_names",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(db_collation="case_insensitive"),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="style",
            name="name",
            field=models.TextField(db_collation="case_insensitive", unique=True),
        ),
    ]
