version: '2'

services:
  postgres:
    image: postgres:12.0
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - REDIS_URL=redis://redis:6379/
    image: web
    build: ./
    command: >
      bash -c "pipenv run python wait_for_postgres.py &&
               pipenv run ./manage.py migrate &&
               pipenv run ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  redis:
    image: "redis:alpine"
  worker:
    restart: always
    image: web
    environment:
      - DJANGO_SECRET_KEY=local
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - postgres
      - redis
    build: ./
    volumes:
      - ./:/code
    command: >
      bash -c "pipenv run python wait_for_postgres.py &&
               pipenv run ./manage.py migrate &&
               pipenv run celery -A hsv_dot_beer worker -l info --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler -O fair"
