# Generated by Django 2.2 on 2019-04-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('tap_list_providers', '0001_initial'), ('tap_list_providers', '0002_auto_20190218_0235'), ('tap_list_providers', '0003_delete_taplistproviderstylemapping')]

    dependencies = [
        ('beers', '0007_auto_20181205_1716'),
    ]

    operations = [
    ]
