# Generated by Django 2.2 on 2019-04-09 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tap_list_providers', '0002_auto_20190218_0235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TapListProviderStyleMapping',
        ),
    ]
