# Generated by Django 2.1.3 on 2018-12-06 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0007_auto_20181205_1716'),
        ('taps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='beer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='taps', to='beers.Beer'),
        ),
    ]
