# Generated by Django 2.1.7 on 2019-02-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_venue_untappd_url'),
        ('taps', '0003_auto_20190201_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='tap',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taps', to='venues.Venue'),
        ),
    ]
