# Generated by Django 2.1.7 on 2019-02-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_venue_untappd_url'),
        ('taps', '0005_move_taps_to_venue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tap',
            unique_together={('venue', 'tap_number')},
        ),
        migrations.RemoveField(
            model_name='tap',
            name='room',
        ),
    ]
