# Generated by Django 3.0.2 on 2020-01-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taps", "0006_auto_20190217_2129"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tap",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="tap",
            constraint=models.UniqueConstraint(
                fields=("venue", "tap_number"), name="venue_tapnumber"
            ),
        ),
    ]
