on:
    push:
        branches:
            - "**"
name: Dev Build
jobs:
    lint-python:
        name: flake8
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Run flake8
              uses: ./.github/actions/lint
    test-www:
        name: Python tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Run Python tests
              run: docker-compose run --rm web bash -c 'export PIPENV_COLORBLIND=1; export PIPENV_NOSPIN=1; pipenv install --dev && pipenv run ./manage.py test'
